//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalUser
    {
        public System.Guid Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public bool IsActive { get; set; }
        public int LoginCount { get; set; }
        public int FailLoginAttempt { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
