//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PortalCustomer> PortalCustomers { get; set; }
        public virtual DbSet<PortalCustomerOrder> PortalCustomerOrders { get; set; }
        public virtual DbSet<PortalErrorMessage> PortalErrorMessages { get; set; }
        public virtual DbSet<PortalPlatformType> PortalPlatformTypes { get; set; }
        public virtual DbSet<PortalProduct> PortalProducts { get; set; }
        public virtual DbSet<PortalProductType> PortalProductTypes { get; set; }
        public virtual DbSet<PortalProvider> PortalProviders { get; set; }
        public virtual DbSet<PortalProvidersProduct> PortalProvidersProducts { get; set; }
        public virtual DbSet<PortalUser> PortalUsers { get; set; }
        public virtual DbSet<PortalSiteMenu> PortalSiteMenus { get; set; }
    }
}
