//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMS.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class PortalProvidersProduct
    {
        public PortalProvidersProduct()
        {
            this.PortalCustomerOrders = new HashSet<PortalCustomerOrder>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public System.Guid ProviderId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid PlatformTypeId { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<PortalCustomerOrder> PortalCustomerOrders { get; set; }
        public virtual PortalPlatformType PortalPlatformType { get; set; }
        public virtual PortalProduct PortalProduct { get; set; }
        public virtual PortalProvider PortalProvider { get; set; }
    }
}
