//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalCustomer
    {
        public PortalCustomer()
        {
            this.PortalCustomerOrders = new HashSet<PortalCustomerOrder>();
            this.Id = Guid.NewGuid();
        }
    
        public System.Guid Id { get; set; }
        public string No { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<PortalCustomerOrder> PortalCustomerOrders { get; set; }
    }
}
